apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  namespace: ie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mypod
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
        - name: mypod
          image: nginx
          resources:
            limits:
              memory: 600Mi
              cpu: 1
            requests:
              memory: 600Mi
              cpu: 500m